name: flexipeer
version: 0.0.1
homepage: https://github.com/prabhuc94/flexi_peer
description: Simple peer-to-peer with WebRTC for Dart. PeerJS port for Flutter.
repository: https://github.com/prabhuc94/flexi_peer
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies: 
  http: ^1.1.0
  uuid: ^4.0.0
  flutter_webrtc: ^0.9.41
  web_socket_channel: ^2.4.0
  events_emitter: ^0.5.2
dev_dependencies: 
  lints: ^2.0.0
  flutter_test: 
    sdk: flutter
